import type { Metadata } from "next";
import { ThemeProvider } from "./utils/themeContext";
import { TransitionProvider } from "./utils/transitionContext";
import { MusicProvider } from "./utils/musicContext";
import { AudioProvider } from "./utils/audioContext";
import { NavProvider } from "./utils/navContext"
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import NavBar from "./components/nav/navBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Elijah Gott - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased text-[14px] md:text-[16px] lg:text-[18px] tracking-tight`}
    >
      <body className="h-full flex flex-col font-sans bg-black">
        <ThemeProvider>
          <TransitionProvider>
            <AudioProvider>
              <MusicProvider>
                <NavProvider>
                  <div className='relative mx-auto my-auto w-full h-full md:h-[90vh] lg:h-[84vh] max-w-[1920px] max-h-270'>
                    {children}
                    <NavBar />
                  </div>
                </NavProvider>
              </MusicProvider>
            </AudioProvider>
          </TransitionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
