import type { Metadata } from "next";
import { MusicProvider } from "./utils/musicContext";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-sans bg-zinc-200 bg-linear-70 from-zinc-300 to-white
      dark:bg-gray-900 dark:bg-linear-70 dark:from-gray-900 dark:to-black">
        <MusicProvider>
          {children}
        </MusicProvider>
      </body>
    </html>
  );
}
