import type { Metadata } from "next";
import { MusicProvider } from "./utils/musicContext";
import { AudioProvider } from "./utils/audioContext";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import NavBar from "./components/nav/navBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Elijah Gott - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="h-full flex flex-col font-sans bg-black
      dark:bg-gray-900 dark:bg-linear-70 dark:from-gray-900 dark:to-black">
        <AudioProvider>
          <MusicProvider>
            <div className="relative mx-auto my-auto w-full max-w-[1920px] sm:h-full md:h-[70vh] min-h-[65vh] max-h-270 bg-linear-70 from-zinc-300 to-white rounded-t-2xl">
              {children}
              <NavBar />
            </div>
          </MusicProvider>
        </AudioProvider>
      </body>
    </html>
  );
}
